import { router } from 'expo-router';
import { LockKeyhole, Mail, UserRound } from 'lucide-react-native';
import React, { useState } from 'react';
import { KeyboardAvoidingView, Platform, StyleSheet, Text, TextInput, View } from 'react-native';
import { AccessiblePressable, AppHeader, PrimaryButton, Screen, safeGoBack } from '@/components/ui';
import { useAuth } from '@/lib/auth';
import { dynamicStyles, F, type ThemeColors, useAppTheme } from '@/lib/theme';

export default function AuthScreen() {
  const theme = useAppTheme(); const { colors: C } = theme; const s = React.useMemo(() => makeStyles(C), [theme.mode, theme.highContrast]);
  const { signIn, signUp, sendReset, updatePassword, recoveryMode, clearRecovery } = useAuth();
  const [mode, setMode] = useState<'signin'|'signup'|'recovery'>(recoveryMode?'recovery':'signin');
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false); const [message, setMessage] = useState('');
  React.useEffect(()=>{if(recoveryMode)setMode('recovery')},[recoveryMode]);
  const submit = async () => { setLoading(true); setMessage(''); const result = mode === 'signin' ? await signIn(email, password) : mode==='signup'?await signUp(name, email, password):await updatePassword(password); setLoading(false); if (result.error) return setMessage(result.error); if (result.confirmationRequired) return setMessage('Check your email to confirm your Kouponly account.'); clearRecovery(); safeGoBack(); };
  const reset = async () => { if (!email.trim()) return setMessage('Enter your email first.'); setLoading(true); const result = await sendReset(email); setLoading(false); setMessage(result.error ?? 'Password reset instructions sent.'); };
  const recovery=mode==='recovery';return <KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={{flex:1}}><Screen testID="auth-screen"><AppHeader eyebrow="YOUR KOUPONLY" title={recovery?'Choose a new password':mode==='signin'?'Welcome back':'Create your account'} back/><Text style={s.intro}>{recovery?'Enter a new password for your Kouponly account.':'Sign in to securely sync saved offers, applications and redemptions. You can always continue in demo mode.'}</Text><View style={s.card}>{mode==='signup'?<Field icon={<UserRound size={18} color={C.muted}/>} label="FULL NAME" value={name} onChangeText={setName} autoComplete="name"/>:null}{!recovery?<Field icon={<Mail size={18} color={C.muted}/>} label="EMAIL" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" autoComplete="email"/>:null}<Field icon={<LockKeyhole size={18} color={C.muted}/>} label={recovery?'NEW PASSWORD':'PASSWORD'} value={password} onChangeText={setPassword} secureTextEntry autoCapitalize="none" autoComplete={mode==='signin'?'current-password':'new-password'}/>{message?<Text accessibilityRole="alert" style={s.message}>{message}</Text>:null}<PrimaryButton testID="auth-submit" loading={loading} disabled={password.length<6||(!recovery&&!email.trim())||(mode==='signup'&&!name.trim())} label={recovery?'Update password':mode==='signin'?'Sign in':'Create account'} onPress={submit}/>{mode==='signin'?<AccessiblePressable haptic="none" accessibilityLabel="Reset password" onPress={reset} style={s.link}><Text style={s.linkText}>Forgot password?</Text></AccessiblePressable>:null}</View>{!recovery?<><AccessiblePressable haptic="selection" accessibilityLabel={mode==='signin'?'Create an account':'Sign in instead'} onPress={()=>{setMode(mode==='signin'?'signup':'signin');setMessage('')}} style={s.switch}><Text style={s.switchText}>{mode==='signin'?'New to Kouponly? Create an account':'Already have an account? Sign in'}</Text></AccessiblePressable><AccessiblePressable haptic="none" accessibilityLabel="Continue in demo mode" onPress={()=>safeGoBack()} style={s.demo}><Text style={s.demoTitle}>Continue in demo mode</Text><Text style={s.demoNote}>Your existing local data stays available on this device.</Text></AccessiblePressable></>:null}</Screen></KeyboardAvoidingView>;
}

function Field({icon,label,...props}:any){return <View style={fieldStyles.field}><Text style={fieldStyles.label}>{label}</Text><View style={fieldStyles.inputRow}>{icon}<TextInput {...props} accessibilityLabel={label.toLowerCase()} style={fieldStyles.input}/></View></View>}
const fieldStyles=dynamicStyles((C)=>StyleSheet.create({field:{marginBottom:14},label:{fontFamily:F.bodyBold,fontSize:11,letterSpacing:1,marginBottom:7,color:C.muted},inputRow:{minHeight:52,borderWidth:1,borderColor:C.line,backgroundColor:C.input,borderRadius:16,flexDirection:'row',alignItems:'center',paddingHorizontal:13},input:{flex:1,minHeight:50,fontFamily:F.body,fontSize:15,paddingHorizontal:10,color:C.ink}}));
const makeStyles=(C:ThemeColors)=>StyleSheet.create({intro:{fontFamily:F.body,fontSize:14,lineHeight:21,color:C.muted,marginTop:-8,marginBottom:18},card:{backgroundColor:C.card,borderWidth:1,borderColor:C.line,borderRadius:24,padding:17},message:{fontFamily:F.bodySemi,fontSize:13,color:C.danger,marginBottom:12},link:{minHeight:44,alignItems:'center',justifyContent:'center'},linkText:{fontFamily:F.bodyBold,fontSize:13,color:C.ink},switch:{minHeight:54,alignItems:'center',justifyContent:'center',marginTop:8},switchText:{fontFamily:F.bodyBold,fontSize:14,color:C.ink},demo:{minHeight:76,borderRadius:20,backgroundColor:C.soft,padding:14,marginTop:10,alignItems:'center',justifyContent:'center'},demoTitle:{fontFamily:F.headingSemi,fontSize:16,color:C.ink},demoNote:{fontFamily:F.body,fontSize:12,color:C.muted,marginTop:4,textAlign:'center'}});
