import { router } from "expo-router";
import { LocateFixed, MapPin, Search, X } from "lucide-react-native";
import React, { useMemo, useState } from "react";
import { Image, ImageBackground, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { AccessiblePressable, Screen } from "@/components/ui";
import { deals } from "@/lib/data";
import { useStore } from "@/lib/store";
import { F,shadow,type ThemeColors,useAppTheme } from "@/lib/theme";
const positions=[{top:"15%",left:"11%"},{top:"27%",left:"62%"},{top:"43%",left:"25%"},{top:"57%",left:"72%"},{top:"69%",left:"43%"},{top:"33%",left:"43%"},{top:"76%",left:"15%"}] as const;
const groups=[{label:"All",categories:[]},{label:"Food",categories:["Dining","Cafes"]},{label:"Beauty",categories:["Beauty"]},{label:"Play",categories:["Activities","Things to do","Entertainment"]},{label:"Stay",categories:["Staycations"]},{label:"Shop",categories:["Shopping"]}];
export default function MapScreen(){const {colors:C}=useAppTheme();const s=useMemo(()=>makeStyles(C),[C]);const [group,setGroup]=useState("All");const [query,setQuery]=useState("");const [focusedId,setFocusedId]=useState(1);const {notify}=useStore();const visible=useMemo(()=>{const active=groups.find(g=>g.label===group)??groups[0];const q=query.trim().toLowerCase();return deals.filter(d=>(!active.categories.length||active.categories.includes(d.category))&&(!q||`${d.name} ${d.place} ${d.category} ${d.offer}`.toLowerCase().includes(q))).slice(0,7)},[group,query]);const focused=visible.find(d=>d.id===focusedId)??visible[0];return <Screen scroll={false} style={s.screen} testID="map-screen">
 <View style={s.top}><View style={{flex:1}}><Text style={s.eyebrow}>KOCHI · CURATED AREA</Text><Text accessibilityRole="header" style={s.title}>Map your next plan.</Text></View><AccessiblePressable accessibilityLabel="Show Centre Square partners" haptic="selection" onPress={()=>{setGroup("All");setQuery("");setFocusedId(3);notify("Showing partners near Centre Square")}} style={s.locate}><LocateFixed size={20} color={C.ink}/></AccessiblePressable></View>
 <View style={s.search}><Search size={18} color={C.ink}/><TextInput accessibilityLabel="Find a partner or offer in Kochi" testID="map-search" value={query} onChangeText={v=>{setQuery(v);if(v)setGroup("All")}} placeholder="Find a partner or offer in Kochi" placeholderTextColor={C.muted} returnKeyType="search" style={s.input}/>{query?<AccessiblePressable accessibilityLabel="Clear map search" onPress={()=>setQuery("")}><X size={18} color={C.ink}/></AccessiblePressable>:null}</View>
 <ScrollView horizontal style={s.filterScroll} showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{groups.map(x=><AccessiblePressable accessibilityState={{selected:group===x.label}} haptic="selection" key={x.label} onPress={()=>{setGroup(x.label);setQuery("")}} style={[s.filter,group===x.label&&s.filterActive]}><Text style={[s.filterText,group===x.label&&s.filterTextActive]}>{x.label}</Text></AccessiblePressable>)}</ScrollView>
 <ImageBackground source={require("../../assets/kochi-map-bg.png")} resizeMode="cover" style={s.map} imageStyle={s.mapImage}><View style={s.mapShade}/><Text style={[s.place,{left:"7%",top:"17%"}]}>EDAPPALLY</Text><Text style={[s.place,{left:"58%",top:"33%"}]}>KALOOR</Text><Text style={[s.place,{left:"16%",top:"50%"}]}>PANAMPILLY NAGAR</Text><Text style={[s.place,{left:"46%",top:"74%"}]}>VYTTILA</Text>{visible.map((d,i)=><Pressable testID={`map-pin-${d.id}`} accessibilityLabel={`Show ${d.name}`} key={d.id} onPress={()=>setFocusedId(d.id)} style={[s.pin,positions[i]]}><View style={[s.pinBubble,focused?.id===d.id&&s.pinActive]}><MapPin size={focused?.id===d.id?25:21} color={focused?.id===d.id?C.ink:"white"} fill={focused?.id===d.id?C.lime:C.ink}/></View></Pressable>)}<View style={s.you}><View/></View></ImageBackground>
 <View style={s.results}><View style={s.resultsHead}><View><Text style={s.eyebrow}>{visible.length} PARTNERS NEARBY</Text><Text style={s.resultsTitle}>{group==="All"?"Best around you":group}</Text></View><Text style={s.area}>{query?`“${query}”`:"Kochi"}</Text></View>{focused?<Pressable testID="map-preview" onPress={()=>router.push(`/deal/${focused.id}`)} style={s.preview}><Image source={{uri:focused.image}} style={s.previewImage}/><View style={{flex:1}}><Text style={s.eyebrow}>{focused.category.toUpperCase()} · {focused.distance}</Text><Text style={s.previewTitle}>{focused.name}</Text><Text style={s.offer} numberOfLines={1}>{focused.offer}</Text><Text style={s.saving}>{focused.saving}</Text></View><Text style={s.arrow}>›</Text></Pressable>:<View style={s.empty}><MapPin size={22}/><View><Text style={s.previewTitle}>No matching partners</Text><Text style={s.offer}>Try another category or search.</Text></View><Pressable onPress={()=>{setGroup("All");setQuery("")}}><Text style={s.reset}>Show all</Text></Pressable></View>}</View>
 </Screen>}
const makeStyles=(C:ThemeColors)=>StyleSheet.create({screen:{paddingHorizontal:0},top:{paddingHorizontal:18,flexDirection:"row",justifyContent:"space-between",alignItems:"center",gap:10},eyebrow:{fontFamily:F.bodyBold,fontSize:11,letterSpacing:1,color:C.ink},title:{fontFamily:F.heading,fontSize:29,color:C.ink,letterSpacing:-1,marginTop:3},locate:{width:44,height:44,borderRadius:16,backgroundColor:C.card,...shadow},search:{marginHorizontal:18,marginTop:13,minHeight:52,borderRadius:16,backgroundColor:C.input,paddingLeft:13,paddingRight:5,flexDirection:"row",alignItems:"center",gap:9,...shadow},input:{flex:1,fontFamily:F.bodySemi,fontSize:14,color:C.ink},filterScroll:{flexGrow:0,maxHeight:68},filters:{paddingHorizontal:18,gap:7,paddingVertical:11},filter:{minHeight:44,borderRadius:22,backgroundColor:C.card,paddingHorizontal:14,justifyContent:"center",borderWidth:1,borderColor:C.line},filterActive:{backgroundColor:C.ink},filterText:{fontFamily:F.bodyBold,fontSize:12,color:C.ink},filterTextActive:{color:C.paper},map:{height:310,marginHorizontal:12,borderRadius:27,overflow:"hidden",borderWidth:1,borderColor:C.line},mapImage:{borderRadius:27},mapShade:{...StyleSheet.absoluteFillObject,backgroundColor:"rgba(255,255,255,.12)"},place:{position:"absolute",fontFamily:F.bodyBold,fontSize:13,letterSpacing:1,color:"rgba(10,10,10,.62)"},pin:{position:"absolute",minWidth:44,minHeight:44,alignItems:"center",justifyContent:"center"},pinBubble:{width:40,height:40,borderRadius:16,backgroundColor:"rgba(255,255,255,.88)",alignItems:"center",justifyContent:"center",...shadow},pinActive:{width:44,height:44,borderRadius:18},you:{position:"absolute",left:"50%",top:"48%",width:24,height:24,borderRadius:12,backgroundColor:C.lime,borderWidth:5,borderColor:"#0A0A0A"},results:{paddingHorizontal:12},resultsHead:{minHeight:60,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},resultsTitle:{fontFamily:F.headingSemi,fontSize:19,color:C.ink,marginTop:2},area:{fontFamily:F.bodyBold,fontSize:11,color:C.muted},preview:{minHeight:108,borderRadius:22,backgroundColor:C.card,padding:10,flexDirection:"row",alignItems:"center",gap:11,...shadow},previewImage:{width:78,height:82,borderRadius:16},previewTitle:{fontFamily:F.headingSemi,fontSize:17,color:C.ink,marginVertical:3},offer:{fontFamily:F.body,fontSize:12,color:C.muted},saving:{fontFamily:F.bodyBold,fontSize:12,color:C.ink,marginTop:4},arrow:{fontSize:30,color:C.ink},empty:{minHeight:94,borderRadius:20,backgroundColor:C.card,padding:13,flexDirection:"row",alignItems:"center",gap:10},reset:{fontFamily:F.bodyBold,fontSize:12,color:C.inkOnAccent,backgroundColor:C.lime,padding:10,borderRadius:10}});
