import { initialState, isValidPartnerPin, makeCode, mergeCloudState, migrateState, reducer, remainingSeconds, replaceWithCloudState } from "../lib/store";
describe("prototype persistence and redemption",()=>{
  it("migrates original state",()=>{const value=migrateState({saved:[1,2],used:[3],campaigns:["brief"]});expect(value.version).toBe(3);expect(value.saved).toEqual([1,2]);expect(value.appliedCampaigns).toEqual(["brief"]);expect(value.savedOffers).toEqual([]);expect(value.points).toBe(680)});
  it("toggles saved state",()=>{const value=reducer(initialState,{type:"toggleSaved",id:1});expect(value.saved).toContain(1);expect(reducer(value,{type:"toggleSaved",id:1}).saved).not.toContain(1)});
  it("marks completed deal redemptions as used",()=>{const value=reducer(initialState,{type:"startRedemption",session:{id:"deal-4",mode:"inStore",status:"pin"}});expect(reducer(value,{type:"updateRedemption",id:"deal-4",patch:{status:"success"}}).used).toContain(4)});
  it("keeps an online offer reserved until completion",()=>{const started=reducer(initialState,{type:"startRedemption",session:{id:"deal-2-1",mode:"online",status:"warning"}});const revealed=reducer(started,{type:"updateRedemption",id:"deal-2-1",patch:{status:"code"}});expect(revealed.used).not.toContain(2);expect(revealed.offerUsage["2-1"]).toBeUndefined();const expired=reducer(revealed,{type:"updateRedemption",id:"deal-2-1",patch:{status:"expired"}});expect(expired.offerUsage["2-1"]).toBeUndefined()});
  it("consumes an online offer once after explicit completion",()=>{const started=reducer(initialState,{type:"startRedemption",session:{id:"deal-2-1",mode:"online",status:"warning"}});const revealed=reducer(started,{type:"updateRedemption",id:"deal-2-1",patch:{status:"code",code:"KPN-02-1234",expiresAt:Date.now()+600000}});const completed=reducer(revealed,{type:"updateRedemption",id:"deal-2-1",patch:{status:"success"}});const reopened=reducer(completed,{type:"updateRedemption",id:"deal-2-1",patch:{status:"success"}});expect(completed.offerUsage["2-1"]).toBe(1);expect(completed.used).toContain(2);expect(reopened.offerUsage["2-1"]).toBe(1);expect(reopened.redemptions["deal-2-1"].code).toBe("KPN-02-1234")});
  it("persists individual saved offers and gifts",()=>{const saved=reducer(initialState,{type:"toggleSavedOffer",id:"2-0"});expect(saved.savedOffers).toContain("2-0");const accepted=reducer(saved,{type:"acceptGift",id:"starbucks-two"});expect(accepted.acceptedGifts).toContain("starbucks-two");const sent=reducer(accepted,{type:"sendGift",offer:"Coffee for two",recipient:"+919999"});expect(sent.sentGifts[0].recipient).toBe("+919999")});
  it("generates codes and handles expiry",()=>{expect(makeCode("deal-2")).toMatch(/^KPN-02-\d{4}$/);expect(remainingSeconds(5000,0)).toBe(5);expect(remainingSeconds(Date.now()-1)).toBe(0);expect(isValidPartnerPin("1234")).toBe(true);expect(isValidPartnerPin("123")).toBe(false)});
  it("deducts reward points once",()=>{const value=reducer(initialState,{type:"redeemReward",id:"coffee",points:200});expect(value.points).toBe(480);expect(reducer(value,{type:"redeemReward",id:"coffee",points:200})).toEqual(value)});
  it("merges cloud state without removing local demo data",()=>{const value=mergeCloudState(initialState,{saved:[4],savedOffers:["4-0"],points:420});expect(value.saved).toEqual(expect.arrayContaining([2,4]));expect(value.savedOffers).toContain("4-0");expect(value.points).toBe(420)});
  it("replaces guest data when an authenticated cloud account loads",()=>{const value=replaceWithCloudState({saved:[4],points:420});expect(value.saved).toEqual([4]);expect(value.saved).not.toContain(2);expect(value.points).toBe(420);expect(value.savedOffers).toEqual([])});
});
